name: Update Changelog
permissions:
  contents: write
on:
  push:
    branches:
      - main
jobs:
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Build changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          outputFile: CHANGELOG.md
      - name: Commit and push changelog
        run: |
          git add CHANGELOG.md
          if git diff --cached --quiet; then
            echo "Changelog unchanged"
            exit 0
          fi
          git commit -m "chore: update changelog" && git push
