name: Update Changelog
on:
  push:
    branches:
      - main
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Generate changelog
        uses: orhun/git-cliff-action@v2
        with:
          output: CHANGELOG.md
      - name: Commit and push changelog
        run: |
          git add CHANGELOG.md
          if git diff --cached --quiet; then
            echo "Changelog unchanged"
            exit 0
          fi
          git commit -m "chore: update changelog" && git push
