name: Go
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Install dependencies
        run: go mod tidy
      - name: Format
        run: gofmt -w $(git ls-files '*.go')
      - name: Vet
        run: go vet ./...
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.55
          args: --timeout=5m
          reporter: github-pr-review
          only-new-issues: true
      - name: Test
        run: go test ./...
